config/routes.rb
Classwork::Application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'schueler', to: 'students', as: 'schueler'
  
  resources :sessions

  resources :users

  resources :answer_students

  resources :tests do
    member do
      get 'state'
    end
  end

  resources :test_students

  resources :questions do
    resources :answers
  end

  resources :categories do
    resources :questions do
      resources :answers
    end
  end

  resources :students

  resources :courses

  resources :groups

  root :to => 'sessions#new'  
end

app/models/answer_student.rb
class AnswerStudent < ActiveRecord::Base
  attr_accessible :answer_id, :student_id, :test_id, :test_student_id, :question_id, :points

  belongs_to :answer
  belongs_to :student
  belongs_to :test 
  belongs_to :question
  belongs_to :test_student

  def self.first_or_create_and_update(answer_id, student_id, test_id)

		#person = Person.find_by_name(name) || Person.new(:name => name)
		#person.update_attributes!(:s
  end

  def self.get_answer_hash(test_student_id)
    a = where(:test_student_id => test_student_id)
    @antworten = Hash.new
    a.each {|i| @antworten[i.answer_id] = i.points}
    @antworten
  end
end

app/controllers/answer_students_controller.rb
class AnswerStudentsController < ApplicationController
  # wird von test_students/show aufgerufen
  def create
    answer = Answer.find(params[:answer_student][:answer_id])
    params[:answer_student][:points] = answer.points
    @answer_student = AnswerStudent.new(params[:answer_student])
    page = params[:page].to_i + 1
    page = page == 1 ? 2 : page
    respond_to do |format|
      if @answer_student.save
        format.html { redirect_to test_student_path(current_session.c_test_student_id, :page => page), notice: 'Auswahl gespeichert.' }
        format.json { render json: @answer_student, status: :created, location: @answer_student }
      else
        format.html { render action: "new" }
        format.json { render json: @answer_student.errors, status: :unprocessable_entity }
      end
    end
  rescue
    redirect_to test_student_path(current_session.c_test_student_id, :page => params[:page]), notice: 'Waehlen Sie eine Antwort.' 
  end

  # PUT /answer_students/1
  # PUT /answer_students/1.json
  def update
    @answer_student = AnswerStudent.find(params[:id])
    page = params[:page].to_i + 1
    respond_to do |format|
      if @answer_student.update_attributes(params[:answer_student])
        format.html { redirect_to test_student_path(current_session.c_test_student_id, :page => page), notice: 'UPDATE erfolgreich.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @answer_student.errors, status: :unprocessable_entity }
      end
    end
  end


  # GET /answer_students
  # GET /answer_students.json
  def index
    @answer_students = AnswerStudent.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @answer_students }
    end
  end

  # GET /answer_students/1
  # GET /answer_students/1.json
  def show
    @answer_student = AnswerStudent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @answer_student }
    end
  end

  # GET /answer_students/new
  # GET /answer_students/new.json
  def new
    @answer_student = AnswerStudent.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @answer_student }
    end
  end

  # GET /answer_students/1/edit
  def edit
    @answer_student = AnswerStudent.find(params[:id])
  end




  # DELETE /answer_students/1
  # DELETE /answer_students/1.json
  def destroy
    @answer_student = AnswerStudent.find(params[:id])
    @answer_student.destroy

    respond_to do |format|
      format.html { redirect_to answer_students_url }
      format.json { head :no_content }
    end
  end
end

app/views/answer_students/_form.html.erb
<%= form_for(@answer_student) do |f| %>
  <% if @answer_student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer_student.errors.count, "error") %> prohibited this question_student from being saved:</h2>

      <ul>
      <% @answer_student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :answer_id %><br />
    <%= f.number_field :answer_id %>
  </div>
  <div class="field">
    <%= f.label :student_id %><br />
    <%= f.number_field :student_id %>
  </div>
  <div class="field">
    <%= f.label :test_id %><br />
    <%= f.number_field :test_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answer_students/edit.html.erb
<h1>Editing question_student</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer_student %> |
<%= link_to 'Back', answer_students_path %>

app/views/answer_students/index.html.erb
<h1>Listing question_students</h1>

<table>
  <tr>
    <th>Question</th>
    <th>Student</th>
    <th>Test</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @question_students.each do |question_student| %>
  <tr>
    <td><%= question_student.question_id %></td>
    <td><%= question_student.student_id %></td>
    <td><%= question_student.test_id %></td>
    <td><%= link_to 'Show', question_student %></td>
    <td><%= link_to 'Edit', edit_question_student_path(question_student) %></td>
    <td><%= link_to 'Destroy', question_student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Question student', new_question_student_path %>

app/views/answer_students/new.html.erb
<h1>New question_student</h1>

<%= render 'form' %>

<%= link_to 'Back', answer_students_path %>

app/views/answer_students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Question:</b>
  <%= @question_student.question_id %>
</p>

<p>
  <b>Student:</b>
  <%= @question_student.student_id %>
</p>

<p>
  <b>Test:</b>
  <%= @question_student.test_id %>
</p>


<%= link_to 'Edit', edit_question_student_path(@question_student) %> |
<%= link_to 'Back', question_students_path %>