config/routes.rb
Classwork::Application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'schueler', to: 'students', as: 'schueler'
  
  resources :sessions

  resources :users

  resources :answer_students

  resources :tests do
    member do
      get 'state'
    end
  end

  resources :test_students

  resources :questions do
    resources :answers
  end

  resources :categories do
    resources :questions do
      resources :answers
    end
  end

  resources :students

  resources :courses

  resources :groups

  root :to => 'sessions#new'  
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :points, :question_id, :text

  belongs_to :question
  has_many :answer_students
end

app/models/answer_student.rb
class AnswerStudent < ActiveRecord::Base
  attr_accessible :answer_id, :student_id, :test_id, :test_student_id, :question_id, :points

  belongs_to :answer
  belongs_to :student
  belongs_to :test 
  belongs_to :question
  belongs_to :test_student

  def self.first_or_create_and_update(answer_id, student_id, test_id)

		#person = Person.find_by_name(name) || Person.new(:name => name)
		#person.update_attributes!(:s
  end

  def self.get_answer_hash(test_student_id)
    a = where(:test_student_id => test_student_id)
    @antworten = Hash.new
    a.each {|i| @antworten[i.answer_id] = i.points}
    @antworten
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  has_many :tests
  has_many :questions
end

app/models/course.rb
class Course < ActiveRecord::Base
  attr_accessible :group_id, :name

  belongs_to :group
  has_many :tests
end

app/models/current_session.rb
class CurrentSession < ActiveRecord::Base
  attr_accessible :course_id, :email, :group_id, :student_id, :courses, :tests, :state, :c_category_id, :c_test_id, :user_id, :c_test_student_id, :c_count_questions, :c_start, :c_duration
    
  serialize :courses
  serialize :tests

  def make(user_id)
   	student = Student.find_by_user_id(user_id)
   	self.user_id = user_id 
   	self.student_id = student.id
   	self.group_id = student.group_id
   	self.email = student.user.email
   	unless self.group_id == 1
   		courses = Course.find_all_by_group_id(student.group_id)
   		courseids = courses.map{|course| course.id}
      self.courses = courseids
      existingtests = courses.map{|c| c.tests unless c.tests.empty? } if courses
      self.tests = existingtests.last.map{|t| t.id unless t.nil? } if existingtests
   		opentests = Test::open_tests
      ctests = opentests.select{|t| t if courseids.include?(t.course_id) }
      self.state = 'logged_in'
      #raise ctests.to_yaml
      ctest = ctests.last
      #raise ctest.to_yaml
      if ctest #&& ctest.first && ctest.first.id > 0
        self.c_category_id = ctest.category_id
   		  self.c_test_id = ctest.id
        self.c_count_questions = Question.find_all_by_category_id(ctest.category_id).count
        self.c_duration = ctest.duration
      end
   	end
   	save
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name

  has_many :courses
  has_many :students
end

app/models/permission.rb
class Permission < Struct.new(:user)
  def allow?(controller, action)
    return true if controller == "sessions"
    return true if controller == "users" && action.in?(%w[new create])
    #return true if controller == "topics" && action.in?(%w[index show])
    if user
      return true if controller == "users" && action.in?(%w[edit update])
      return true if controller == "test_students"
      return true if controller == "answer_students"
      return true if user.student.group.name == 'Lehrer'
    end
    false
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :category_id, :status, :text, :answers_attributes

  has_many :answers
  has_many :answer_students
  belongs_to :category

  accepts_nested_attributes_for :answers, allow_destroy: true
  #named_scope :previous, lambda { |p| {:conditions => ["id < ?", p.id], :limit => 1, :order => "id"} }
	#named_scope :next, lambda { |p| {:conditions => ["id > ?", p.id], :limit => 1, :order => "id"} }
end	

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :group_id, :user_id

  has_many :answer_students
  has_many :test_students
  belongs_to :group 
  belongs_to :user
end

app/models/test.rb
class Test < ActiveRecord::Base
    attr_accessible :category_id, :course_id, :description, :duration

    has_many :test_students
    belongs_to :course 
    belongs_to :category

    has_many :events, class_name: "TestEvent"

    STATES = %w[new open canceled shipped closed]
    delegate :new?, :open?, :canceled?, :shipped?, :closed?, to: :current_state

    def self.open_tests
      #joins(:events).merge TestEvent.with_last_state("open")
      joins(:events).where("test_events.id IN (SELECT MAX(id) FROM test_events GROUP BY test_id) AND state = 'open'")
    end

    def current_state
      (events.last.try(:state) || STATES.first).inquiry
    end

    def purchase(valid_payment = true)
      if new?
        # process purchase ...
        events.create! state: "open" if valid_payment
      end
    end

    def change(state)
      events.create! state: state
    end

    def resume
      events.create! state: "open" if canceled?
    end

    def ship
      events.create! state: "shipped" if open?
    end

end

app/models/test_event.rb
class TestEvent < ActiveRecord::Base
  belongs_to :test
  attr_accessible :state, :test_id

  validates_presence_of :test_id
  validates_inclusion_of :state, in: Test::STATES

  #!! Method nicht verwenden, funktioniert nur unter sqlite
  def self.with_last_state(state)

    #order("id desc").group("test_id").having(state: state) #original, gibt aber bei mysql einen Fehler 

    #order("id desc").group("test_id").where(state: state) #ergaenzt den select um eine Tabelle, funktioniert aber nicht korrekt. Siehe unten
    #SELECT `tests`.* FROM `tests` INNER JOIN `test_events` ON `test_events`.`test_id` = `tests`.`id` GROUP BY test_events.test_id HAVING `test_events`.`state` = 'open' ORDER BY tests.id desc;
    #Aenderung:
    #SELECT `tests`.*, test_events.* FROM `tests` INNER JOIN `test_events` ON `test_events`.`test_id` = `tests`.`id` GROUP BY test_events.test_id HAVING `test_events`.`state` = 'open' ORDER BY tests.id desc;
    
    order("id desc").group("test_id").having(state: state)
  end
end

app/models/test_student.rb
class TestStudent < ActiveRecord::Base
  attr_accessible :end, :points, :start, :student_id, :test_id, :current_question_id, :count_questions

  belongs_to :student 
  belongs_to :test 
  has_many :answer_students, :dependent => :destroy
  
  def test_exists(user_id)

  end
end

app/models/user.rb
class User < ActiveRecord::Base
  #attr_accessible :email, :password_hash, :password_salt
  attr_accessible :email, :password, :password_confirmation

  validates_uniqueness_of :email
	validates :email, :presence => true, :email_format => true

  has_secure_password

  has_one :student,:dependent => :destroy
  #accepts_nested_attributes_for :student

  after_create :send_mail

  protected

  def send_mail
  	UserMailer.registration_confirmation(self).deliver
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr">
<head>
  <title>G16 Klassenarbeiten</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%#= javascript_include_tag controller.controller_name %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="header">
	<div class="center_wrapper">
		
		<div id="toplinks">
			<div id="toplinks_inner"><%#= current_user.email %>
				<% if current_user %>
					<%= current_user.email %><%= " (Admin)" if admin? %> 
					<%= link_to "Log Out", logout_path%> 
				<% else %>
					<%= link_to "Sign Up", signup_path %>
					or
					<%= link_to "Log In", login_path %>
				<% end %>

			</div>
		</div>
		<div class="clearer">&nbsp;</div>

		<div id="site_title">
		  <%= image_tag 'g16_logo.png', :size => '280x100' %>
		  <div style="float:right;margin-right:50px;">
			<h1><a href="#">Klassenarbeiten<span></span></a></h1>
			<p>Konfigurieren und Administrieren</p>
			</div>
		</div>

	</div>
</div>

<div id="navigation">
	<div class="center_wrapper">
		<% if admin? %>
		<ul>
			<li><%= link_to "Tests", tests_path %></li>
			<li><%= link_to "Fragen", categories_path %></li>
			<li><%= link_to "Benutzer", users_path %></li>
		</ul>
		<% end %>
		<div class="clearer">&nbsp;</div>
	</div>
</div>

<div id="layout_body">
	
	<div id="main_wrapper_outer">
		<div id="main_wrapper_inner">
			<div class="center_wrapper">
        <% if flash.present? %>
          <div id='flash'>
            <% flash.each do |type, message| -%>
              <div class="message <%= type %>">
                <%= message %>
              </div>
            <% end -%>
          </div>
        <% end %>
			
				<p><%= yield %></p>

				<div class="clearer">&nbsp;</div>
			</div>
		</div>
	</div>

</div>

<div id="dashboard">
	<div id="dashboard_content">
		<div class="center_wrapper">

			<div class="col3 left">
				<div class="col3_content">
					<h4>Tools</h4>
					<ul>
						<li><a href="#"></a></li>
						<li><a href="#"></a></li>
					</ul>
				</div>
			</div>

			<div class="col3mid left">
				<div class="col3_content">
					<h4>Infos</h4>
					<ul>
						<li><a href="#"></a></li>
					</ul>
				</div>
			</div>

			<div class="col3 right">
				<div class="col3_content">
					<h4>Links</h4>
					<ul>
						<li><a href="#"></a></li>
						<li><a href="#"></a></li>
					</ul>
				</div>
			</div>

			<div class="clearer">&nbsp;</div>

		</div>
	</div>
</div>

<div id="footer">
	<div class="center_wrapper">

		<div class="left">
			&copy; 2012 - Thomas Bogner
		</div>
		<div class="right">
			<a href="http://templates.arcsin.se/">Website template</a> by <a href="http://arcsin.se/">Arcsin</a> 
		</div>
		
		<div class="clearer">&nbsp;</div>

	</div>
</div>

</body>
</html>